# Generated by Django 2.2 on 2021-01-09 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0002_notification_model_not_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification_model',
            old_name='not_type',
            new_name='notification_type',
        ),
    ]
