# Generated by Django 2.2 on 2021-01-09 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0004_auto_20210109_1726'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notification_model',
        ),
    ]
