# Generated by Django 2.2 on 2021-01-09 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification_app', '0007_auto_20210109_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification_pref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfs_daily', models.BooleanField(default=False)),
                ('rfs_week', models.BooleanField(default=False)),
                ('comment_mention', models.BooleanField(default=False)),
                ('comment_reply', models.BooleanField(default=False)),
                ('play_sound', models.BooleanField(default=False)),
                ('before_auction', models.BooleanField(default=False)),
                ('new_bids', models.BooleanField(default=False)),
                ('new_comments', models.BooleanField(default=False)),
                ('questions_answered', models.BooleanField(default=False)),
                ('auction_results', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
