# Generated by Django 2.2 on 2021-01-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0008_notification_pref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification_model',
            name='notification_type',
            field=models.BooleanField(default=False),
        ),
    ]
