# Generated by Django 2.2 on 2021-01-07 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_amount_percentage', models.FloatField(default=0.0)),
                ('seller_amount_percentage', models.FloatField(default=0.0)),
                ('status', models.PositiveIntegerField(choices=[(0, 'Failed'), (1, 'Success')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auction_buyer', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auction_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
