# Generated by Django 2.2 on 2021-01-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auction',
            name='current_bid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auction',
            name='ends_in',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='auction',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='auction',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='auction',
            name='total_bids',
            field=models.IntegerField(default=9),
        ),
    ]
