# Generated by Django 2.2 on 2021-01-06 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=200)),
                ('zip_code', models.IntegerField(default=0)),
                ('country', models.CharField(default='', max_length=100)),
                ('card_holder', models.CharField(default='', max_length=100)),
                ('card_number', models.IntegerField(default=1234123412341234)),
                ('cvc', models.IntegerField(default=123)),
                ('expiration', models.DateField()),
                ('picture', models.ImageField(upload_to='profile')),
                ('password_key', models.CharField(default='', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
