# Generated by Django 2.2 on 2021-01-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_auto_20210107_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expiration_month',
            field=models.CharField(default='DECEMBER', max_length=100),
        ),
    ]
