# Generated by Django 2.2 on 2021-01-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0006_payment_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_keys',
            name='customer_Id',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='payment_keys',
            name='payment_method_key',
            field=models.CharField(default='', max_length=150),
        ),
    ]
